import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

//this takes baseURL, calls reducerFunction, expected Tages
// endpoints: creates getRequest to new URL generated by changing id from db, and returs tag
// we set express router; that whenever get request to "/user/:id" calls controller/generl.js
//general.js
/*  which returns {
    id : number { gets from generated url} 
    user : json object of that id
 }
 */
//here: query : json object of that id from db

//exports: 
// api: {
//     baseQuery, fetchBaseQuery, tagtypes, and query:json object
// }

export const api = createApi({
    baseQuery: fetchBaseQuery({ baseUrl: process.env.REACT_APP_BASE_URL }),
    reducerPath: "adminApi",
    tagTypes: [
        "User",
        "Products",
        "Customers",
        "Transactions",
        "Geography",
        "Sales",
        "Admins",
        "Performance",
        "Dashboard",
    ],
    endpoints: (build) => ({
        //only send get requests as 
        getUser: build.query({
            query: (id) => `general/user/${id}`, //saves json object of that id form db
            providesTags: ["User"],
        })
    })
})

export const {
    useGetUserQuery, //returns flags and url

} = api